// Code generated by MockGen. DO NOT EDIT.
// Source: internal/broadcaster/broadcaster.go
//
// Generated by this command:
//
//	mockgen --source=internal/broadcaster/broadcaster.go --destination=internal/mocks/mock_broadcaster.go --package=mocks --mock_names=Broadcaster=MockBroadcaster
//

// Package mocks is a generated GoMock package.
package mocks
