// Code generated by MockGen. DO NOT EDIT.
// Source: internal/manager/controller/manager/controller.go
//
// Generated by this command:
//
//	mockgen --source=internal/manager/controller/manager/controller.go --destination=internal/mocks/mock_manager_controller.go --package=mocks --mock_names=Service=MockService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// PublishMessage mocks base method.
func (m *MockService) PublishMessage(msg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishMessage", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishMessage indicates an expected call of PublishMessage.
func (mr *MockServiceMockRecorder) PublishMessage(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMessage", reflect.TypeOf((*MockService)(nil).PublishMessage), msg)
}
